### ISSUE TITLE
AttributeError: 'Genie' object has no attribute '_generate_page_with',如何解决？

### ISSUE THREAD

**Issue by luckypoem** [skyline75489/Genie#1]
hi,

root@AR:~/genie# python genie.py
Find 1 articles
Start rendering
Done
Traceback (most recent call last):
  File "genie.py", line 193, in <module>
    main()
  File "genie.py", line 190, in main
    g.update()
  File "genie.py", line 185, in update
    self.render()
  File "genie.py", line 180, in render
    self.generate_index()
  File "genie.py", line 113, in generate_index
    self._generate_page_with(
AttributeError: 'Genie' object has no attribute '_generate_page_with'
root@AR:~/genie#

谢谢你

**Comment by luckypoem** [comment]
hi。 
博客是建立起来了：http://surmount.biz.st:3424 ，但是我在同一天发的帖子，排列的顺序不是按时间顺序排列的。即使我在2016-07-06的后面加上"_2101_",帖子还是随机排列的，如何解决呢？

root@AR:~/genie/src# ls
2016-07-06_2101_test1.md  2016-07-06_2105_test5.md
2016-07-06_2102_test2.md  2016-07-06_2106_chinese_economy.md
2016-07-06_2103_test3.md  2016-07-06_2107_air_disaster.md
2016-07-06_2104_test4.md
root@AR:~/genie/src#

**Comment by skyline75489** [comment]
这是代码的问题，我只取到了“天”这一个级别，再细的时间没有做处理。
